### ISSUE TITLE
"Google Chrome : Install Addon" button resolves to a 404 page

### ISSUE THREAD

**Issue by durhambell** [subhra74/xdm#39] opened 2020-03-06 18:40 UTC
**Describe the bug**
The in app link to the Chrome store extension resolves to a 404.

**To Reproduce**
1. Go to
2. Click on "Settings (Gear) icon", click "Browser Monitoring: View Settings"
3. Scroll down to 'Google Chrome: Install Addon'
4. See error (screenshot below)

**Expected behavior**
Expected link to resolve to an active store app.

**Screenshots**
![image](https://user-images.githubusercontent.com/9648408/76111316-0d481f00-5fae-11ea-930b-2c8edeac418b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10.0.18363
 - Browser: Chrome (but any that access the store, since it doesn't come up on search either)
 - Version: 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
It seems as though Google/Chrome has purged the page from the store (automatically or otherwise).

**Comment by subhra74** [comment] 2020-03-07 09:29
The browser extension was disabled by chrome webstore without any prior notification. The cause was “ Need to mention details in the description about requirements needed for the extension to run properly”. I have modified the description and resubmitted the extension for publication again, but not sure when they will finish review and publish it.

**Comment by SweetyVolty** [comment] 2020-03-07 18:40
Can we have the Crx for it cause chromium based crx not working with chrome :'(

**Comment by cann357** [comment] 2020-03-08 05:34
I hope they publish it again cause no others program does what yours does

**Comment by subhra74** [comment] 2020-03-08 06:19
> Can we have the Crx for it cause chromium based crx not working with chrome :'(

CRX won't work in Google chrome, because they only allow extension from chrome web store only

**Comment by subhra74** [comment] 2020-03-08 06:19
> I hope they publish it again cause no others program does what yours does

I hope that too

**Comment by 3xploiton3** [comment] 2020-03-12 17:26
for chromium try install manual

https://www.crx4chrome.com/crx/80378/

tested in vivaldi,

**Comment by subhra74** [comment] 2020-03-16 17:22
The extension is available now on chrome web store:
[](https://chrome.google.com/webstore/detail/xtreme-download-manager/dkckaoghoiffdbomfbbodbbgmhjblecj)

**Comment by candrapersada** [comment] 2020-03-16 21:55
add notification for replace chrome web store for all user

**Comment by subhra74** [comment] 2020-03-16 23:09
New 2020 version will be released soon with the updated link for the extension

**Comment by candrapersada** [comment] 2020-03-16 23:31
fix video download from https://www.animegg.org/cardfight-vanguard-zoku-koukousei-hen-episode-43#subbed #31

**Comment by candrapersada** [comment] 2020-03-18 01:36
why the video download panel page titles do not match or complete with the browser page title
issues #17

**Closed** 2020-03-25 18:51 UTC

**Comment by Deepanshu81** [comment] 2020-05-29 04:59
The new extension link is not working

**Comment by uhbot223** [comment] 2020-05-29 22:42
yeah its not working again

**Comment by CPCer** [comment] 2022-04-26 01:07
extension page reads

An error has occurred
Could not unzip extension

**Comment by febqij** [comment] 2022-10-11 11:39
How do I understand the extension is dead and buried?

**Comment by fluffoid** [comment] 2022-11-24 03:11
Sad state of affairs.

**Comment by TommmiDE** [comment] 2023-07-01 11:47
404 again
