### ISSUE TITLE
Download the Chinese file, the file name will be garbled.

### ISSUE THREAD

**Issue by chenxinss** [subhra74/xdm#110] opened 2020-04-11 09:38 UTC
Download the Chinese file, the file name will be garbled.

**Comment by vandpurnama** [comment] 2020-04-13 12:30
it's a bug on xdm same reported issue #76 i got that problem too downloading file with korean or japanese language

**Comment by subhra74** [comment] 2020-04-14 08:45
> it's a bug on xdm same reported issue #76 i got that problem too downloading file with korean or japanese language

@vandpurnama 
thanks

**Comment by ardypro** [comment] 2020-05-24 11:46
It seems XDM support ASCII characters only

**Comment by subhra74** [comment] 2020-05-24 19:35
The issue is with Java fonts, i am looking into it.

**Comment by objectProgrammer** [comment] 2020-11-17 22:15
@subhra74 It's not related to fonts. Fonts are only used to display characters, if the font didn't support it would just show a square not garbled data. It's related to the url-decoding algorithm, which I've fixed in #394.

**Closed** 2021-01-17 13:19 UTC
Labels: duplicate, question
