### ISSUE TITLE
command line path for ffmpeg not working

### ISSUE THREAD

**Issue by petemarkey** [subhra74/xdm#214] opened 2020-06-02 22:45 UTC
Downloading a video from the internet in google chrome on windows 10.
All parts appear to download successfully.
It errors out concatenating the parts together. 
"Failed to append/convert file parts, please check if drive is full or write protect"

I ran the program in debug mode and got the arguments sent to ffmpeg.
The target file name is 1.ts in folder C:\Videos.
Temp folder is D:\xdmtemp

This from the console mode when i try to complete the download.

[ AWT-EventQueue-0 ] Restore success
[ AWT-EventQueue-0 ] List changed
[ Thread-4 ] checking for same named file on disk...
[ Thread-4 ] Updating file name- old: 1.ts new: 1.ts
[ Thread-4 ] Outformat: Original
[ Thread-4 ] @ffmpeg_args: C:\Program Files (x86)\XDM\ffmpeg.exe
[ Thread-4 ] @ffmpeg_args: -f
[ Thread-4 ] @ffmpeg_args: concat
[ Thread-4 ] @ffmpeg_args: -safe
[ Thread-4 ] @ffmpeg_args: 0
[ Thread-4 ] @ffmpeg_args: -i
[ Thread-4 ] @ffmpeg_args: D:\xdmtemp\175277fa-f480-4866-8c5c-4ceab7a43cd9\175277fa-f480-4866-8c5c-4ceab7a43cd9-hls.txt
[ Thread-4 ] @ffmpeg_args: -acodec
[ Thread-4 ] @ffmpeg_args: copy
[ Thread-4 ] @ffmpeg_args: -vcodec
[ Thread-4 ] @ffmpeg_args: copy
[ Thread-4 ] @ffmpeg_args: C:\Videos\62948448-dbfc-46c3-9c95-77d09ee45d97_1.ts
[ Thread-4 ] @ffmpeg_args: -y
[ Thread-4 ] FFmpeg exit code: 30
[ Thread-4 ] java.io.IOException: FFmpeg failed
        at xdman.downloaders.hls.HlsDownloader.assemble(HlsDownloader.java:647)
        at xdman.downloaders.hls.HlsDownloader$1.run(HlsDownloader.java:577)
        at java.base/java.lang.Thread.run(Unknown Source)
[ Thread-4 ] List updated
[ Thread-4 ] removed
[ Thread-3 ] java.io.IOException: Unexpected EOF while reading header line
        at xdman.util.NetUtils.readLine(NetUtils.java:18)
        at xdman.monitoring.Request.read(Request.java:16)
        at xdman.monitoring.MonitoringSession.serviceRequest(MonitoringSession.java:485)
        at xdman.monitoring.MonitoringSession.run(MonitoringSession.java:516)
        at java.base/java.lang.Thread.run(Unknown Source)

**I tried to run the command at the command line with following command and get the following error:**

C:\Program Files (x86)\XDM>ffmpeg.exe -f concat -safe 0 -i D:\xdmtemp\175277fa-f480-4866-8c5c-4ceab7a43cd9\175277fa-f480-4866-8c5c-4ceab7a43cd9-hls.txt -acodec copy -vcodec copy C:\Videos\baf32d25-91f8-4e48-b610-07d9a9cdc218_1.ts -y
ffmpeg version git-2020-05-15-b18fd2b Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3.1 (GCC) 20200513
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 45.100 / 56. 45.100
  libavcodec     58. 84.100 / 58. 84.100
  libavformat    58. 43.100 / 58. 43.100
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 81.100 /  7. 81.100
  libswscale      5.  6.101 /  5.  6.101
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
[concat @ 0721d2c0] Impossible to open 'DD:\xdmtemp\175277fa-f480-4866-8c5c-4ceab7a43cd9\db227fc8-4e93-42c8-97da-f78e12b912ae'
D:\xdmtemp\175277fa-f480-4866-8c5c-4ceab7a43cd9\175277fa-f480-4866-8c5c-4ceab7a43cd9-hls.txt: Protocol not found
Did you mean file:D:\xdmtemp\175277fa-f480-4866-8c5c-4ceab7a43cd9\175277fa-f480-4866-8c5c-4ceab7a43cd9-hls.txt?

**Comment by petemarkey** [comment] 2020-06-02 23:12
The file that ffmpeg is finding impossible to open:  'DD:\xdmtemp\175277fa-f480-4866-8c5c-4ceab7a43cd9\db227fc8-4e93-42c8-97da-f78e12b912ae'

is the first file in the "manifest", listed as:

file 'D:\xdmtemp\175277fa-f480-4866-8c5c-4ceab7a43cd9\db227fc8-4e93-42c8-97da-f78e12b912ae'

**Comment by subhra74** [comment] 2020-06-03 17:23
Duplicate of #198 #212 
For resolution please see #212

**Closed** 2020-06-03 18:05 UTC
Labels: duplicate
