### ISSUE TITLE
'javasharedresources' folder in my user's home directory.

### ISSUE THREAD

**Issue by f4him** [subhra74/xdm#271] opened 2020-07-25 13:19 UTC
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

After I install xdm a folder named 'javasharedresources' is automatically created in my home directory. Do I need this folder after complete and successful installation? If I do, can I put it somewhere else and link it to xdm somehow?

**Comment by subhra74** [comment] 2020-08-05 07:08
Duplicate #161 
For now you can delete it, but will get recreated. Will be fixed in future version

**Comment by Zahid-BM** [comment] 2020-09-04 15:58
That means is it a bug? When I delete and again auto create. Opps.

**Comment by lincolnokaalo** [comment] 2021-01-15 09:55
https://sourceforge.net/p/xdman/discussion/general/thread/d12cd8c466/?limit=25 

This fixed it for me: 'Kali GNU/Linux Rolling'

**Comment by cansozbir** [comment] 2021-08-19 23:53
It is still the same :(

**Comment by lospejos** [comment] 2021-09-22 10:56
AFAIK 
This is a cache directory for the OpenJ9 Java runtime (java class files compiled to native code). It will be reacreated until you use Open J9 Java runtime (JDK or JRE).
See also here: https://github.com/subhra74/xdm/issues/161

**Comment by subhra74** [comment] 2021-09-28 19:13
Next release will fix this problem

**Closed by subhra74** 2021-09-28 19:13 UTC
Labels: duplicate, question

**Comment by santhoshunt** [comment] 2022-01-16 06:09
Still this issue is not fixed!😢

**Comment by Accidentaccio** [comment] 2022-10-19 20:21
to date it has not yet been resolved

**Comment by abdulrahmanrahhal** [comment] 2023-01-10 18:32
Still not fixed.

**Comment by Yab1** [comment] 2023-01-25 14:11
Still not fixed

**Comment by aakashumariya-43** [comment] 2023-03-09 05:20
Still not fixed

**Comment by sloke123** [comment] 2024-03-08 11:33
Still not fixed 😑

**Comment by gargujjwal** [comment] 2024-12-26 12:13
the issue is still not fixed###

**Comment by NevahLucky** [comment] 2025-06-12 15:25
I guess I'll add on to the chain, S.N.F.
